# Makefile for offline installation of opencode-chat-bridge.
#
# All targets use only files in this checkout. No Docker images,
# no registry, no network. A populated ./node_modules/ is required
# (typically bundled in the release tarball; populate once with
# 'bun install --frozen-lockfile' if you only have a git checkout).
#
# Use 'make help' to list targets.

SHELL := /bin/sh

# ---- Configuration (override on command line) ---------------------------

PREFIX       ?= /usr/local
USER_PREFIX  ?= $(HOME)/.local
DESTDIR      ?=
SRC_DIR      := $(CURDIR)

BIN_DIR        := $(DESTDIR)$(PREFIX)/bin
SHARE_DIR      := $(DESTDIR)$(PREFIX)/share/opencode-chat-bridge
USER_BIN_DIR   := $(DESTDIR)$(USER_PREFIX)/bin
USER_SHARE_DIR := $(DESTDIR)$(USER_PREFIX)/share/opencode-chat-bridge

# Connector entry points: each becomes a wrapper named
# 'opencode-chat-bridge-<name>' that runs 'bun ./connectors/<name>.ts'
# from the install dir.
CONNECTORS := matrix slack telegram discord whatsapp mattermost web

.DEFAULT_GOAL := help

# ---- help ----------------------------------------------------------------

.PHONY: help
help: ## List all targets with descriptions and the overridable variables
	@printf "opencode-chat-bridge - offline installer\n\nUsage: make [target] [VAR=value ...]\n\nTargets:\n"
	@awk 'BEGIN {FS = ":.*## "} \
	/^[a-zA-Z_-]+:.*## / {printf "  \033[36m%-18s\033[0m %s\n", $$1, $$2}' \
	$(MAKEFILE_LIST) | sort -u
	@printf "\nVariables (override: make VAR=value target):\n"
	@printf "  \033[36m%-18s\033[0m %s\n" "PREFIX"       "system prefix (default '$(PREFIX)')"
	@printf "  \033[36m%-18s\033[0m %s\n" "USER_PREFIX"  "per-user prefix (default '$(USER_PREFIX)')"
	@printf "  \033[36m%-18s\033[0m %s\n" "DESTDIR"      "stage root for packaging (default unset)"

# ---- guards --------------------------------------------------------------

.PHONY: guard-deps
guard-deps:
	@if [ ! -d "$(SRC_DIR)/node_modules" ]; then \
	  echo "ERROR: $(SRC_DIR)/node_modules/ is missing." 1>&2; \
	  echo "The installer needs a populated dependencies tree." 1>&2; \
	  echo "Either obtain the released tarball (which bundles it), or" 1>&2; \
	  echo "with network, run once:  bun install --frozen-lockfile" 1>&2; \
	  exit 1; \
	fi

# ---- install-user --------------------------------------------------------

.PHONY: install-user
install-user: guard-deps ## Per-user install into $(USER_PREFIX); no root required
	@mkdir -p "$(USER_BIN_DIR)" "$(USER_SHARE_DIR)"
	@cp -R "$(SRC_DIR)/connectors"   "$(USER_SHARE_DIR)/"
	@cp -R "$(SRC_DIR)/src"          "$(USER_SHARE_DIR)/"
	@cp -R "$(SRC_DIR)/node_modules" "$(USER_SHARE_DIR)/"
	@cp    "$(SRC_DIR)/package.json" \
	       "$(SRC_DIR)/bun.lock" \
	       "$(SRC_DIR)/tsconfig.json" \
	       "$(USER_SHARE_DIR)/"
	@$(MAKE) --no-print-directory gen-wrappers \
	    BIN_DIR="$(USER_BIN_DIR)" SHARE_DIR="$(USER_SHARE_DIR)"
	@echo
	@echo "Per-user install complete."
	@echo "  project copy : $(USER_SHARE_DIR)"
	@echo "  wrappers     : $(USER_BIN_DIR)/opencode-chat-bridge-*"
	@echo "  tip          : ensure '$(USER_BIN_DIR)' is on PATH"

# ---- install-system ------------------------------------------------------

.PHONY: install-system
install-system: guard-deps ## Systemwide install into $(PREFIX); typically needs root
	@mkdir -p "$(BIN_DIR)" "$(SHARE_DIR)"
	@cp -R "$(SRC_DIR)/connectors"   "$(SHARE_DIR)/"
	@cp -R "$(SRC_DIR)/src"          "$(SHARE_DIR)/"
	@cp -R "$(SRC_DIR)/node_modules" "$(SHARE_DIR)/"
	@cp    "$(SRC_DIR)/package.json" \
	       "$(SRC_DIR)/bun.lock" \
	       "$(SRC_DIR)/tsconfig.json" \
	       "$(SHARE_DIR)/"
	@$(MAKE) --no-print-directory gen-wrappers \
	    BIN_DIR="$(BIN_DIR)" SHARE_DIR="$(SHARE_DIR)"
	@echo
	@echo "Systemwide install complete."
	@echo "  project copy : $(SHARE_DIR)"
	@echo "  wrappers     : $(BIN_DIR)/opencode-chat-bridge-*"

# ---- gen-wrappers (internal) --------------------------------------------

.PHONY: gen-wrappers
gen-wrappers:
	@for c in $(CONNECTORS); do \
	  out="$(BIN_DIR)/opencode-chat-bridge-$$c"; \
	  printf '%s\n%s\n%s\nINSTALL_DIR=%s\n%s\nexec bun %s "$$@"\n' \
	    '#!/bin/sh' \
	    '# Auto-generated by the opencode-chat-bridge Makefile.' \
	    'set -e' \
	    "$(SHARE_DIR)" \
	    'cd "$$INSTALL_DIR" || exit 1' \
	    "./connectors/$$c.ts" > "$$out"; \
	  chmod 0755 "$$out"; \
	  echo "  wrapper: $$out"; \
	done

# ---- uninstall-user ------------------------------------------------------

.PHONY: uninstall-user
uninstall-user: ## Remove the per-user install (under $(USER_PREFIX))
	@for c in $(CONNECTORS); do rm -f "$(USER_BIN_DIR)/opencode-chat-bridge-$$c"; done
	@rm -rf "$(USER_SHARE_DIR)"
	@echo "Removed $(USER_SHARE_DIR)"
	@echo "Removed opencode-chat-bridge-* wrappers from $(USER_BIN_DIR)"

# ---- uninstall-system ----------------------------------------------------

.PHONY: uninstall-system
uninstall-system: ## Remove the systemwide install (under $(PREFIX))
	@for c in $(CONNECTORS); do rm -f "$(BIN_DIR)/opencode-chat-bridge-$$c"; done
	@rm -rf "$(SHARE_DIR)"
	@echo "Removed $(SHARE_DIR)"
	@echo "Removed opencode-chat-bridge-* wrappers from $(BIN_DIR)"
